server:
  port: 80


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka


ribbon:
  ReadTimeout:  5000      #OpenFeign超时控制  最长读取时间
  ConnectTimeout: 5000    #OpenFeign超时控制  最长建立连接时间


logging:
  level:
    com.service.PaymentFeignService: debug      #OpenFeign日志打印功能

